--  Find Popular Tags
-- SELECT t.tag_name, COUNT(pt.photo_id) AS photo_count
-- FROM tags t
-- JOIN photo_tags pt ON t.tag_id = pt.tag_id
-- GROUP BY t.tag_name
-- ORDER BY photo_count DESC
-- LIMIT 3;